# This section contains the Compose file that describes your application services.
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: ${mysql.user}
       MYSQL_PASSWORD: ${mysql.password}

   wordpress:
     depends_on:
       - db
     image: wordpress:${wordpress.version}
     ports:
       - "${port}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${mysql.user}
       WORDPRESS_DB_PASSWORD: ${mysql.password}
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
