apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;

        sendfile        on;

        keepalive_timeout  65;


        server {
            listen 80;
            listen [::]:80;

            location / {
                proxy_set_header Host $host;
                proxy_pass https://www.seznam.cz/;
            }
        }
    }
