# syntax=docker/dockerfile:1.0.0-experimental

FROM alpine

RUN apk add --no-cache openssh-client git
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

RUN --mount=type=ssh git clone git@bitbucket.org:bscideas/rbcz-be.git
RUN ls -all rbcz-be
