# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wlp'
    scheme: 'https'
    static_configs:
      - targets: ['docker.for.mac.localhost:9443']
    basic_auth:
      username: admin
      password: adminpwd
    tls_config:
      insecure_skip_verify: true
